Repository osism/container-image-kolla-ansible, pull requests merged in 2021-05, with the labels that each got.

#158 Only remove 99-netbox.yml if /ansible/inventory is writable
  files/scripts/master/run.sh
  files/scripts/rocky/run.sh
  files/scripts/stein/run.sh
  files/scripts/train/run.sh
  files/scripts/ussuri/run.sh
  files/scripts/victoria/run.sh
Labels: Type: Bugfix

#159 Use the ansible-defaults repository
  Dockerfile
  files/images.yml
  files/scripts/generate-images-file.py
Labels: Type: Feature

#160 Allow manual workflow triggering
  .github/workflows/build-docker-image.yml
Labels: Type: CI
